# Generated by Django 5.1.7 on 2025-12-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoria', models.JSONField(default=dict)),
                ('contexto', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Chatbots',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('humano', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id_tablero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=50)),
                ('estado_casillas', models.JSONField()),
                ('historial', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Tableros',
            },
        ),
        migrations.CreateModel(
            name='IA',
            fields=[
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.jugador')),
                ('nivel', models.IntegerField()),
            ],
            options={
                'verbose_name': 'IA',
                'verbose_name_plural': 'IAs',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id_partida', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada')], default='EN_CURSO', max_length=20)),
                ('numero_jugadores', models.IntegerField()),
                ('jugador_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_actual', to='game.jugador')),
            ],
            options={
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id_pieza', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=10)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='game.jugador')),
            ],
            options={
                'verbose_name_plural': 'Piezas',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='game.partida')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=10)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.jugador')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pieza')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='game.turno')),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
