# Generated by Django 5.1.7 on 2025-12-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='tablero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partida', to='game.tablero'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='jugador_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_actual', to='game.jugador'),
        ),
    ]
