# Generated by Django 5.1.7 on 2025-12-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_partida_tablero_alter_partida_jugador_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='ia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot', to='game.ia'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='tablero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot', to='game.tablero'),
        ),
        migrations.AddField(
            model_name='ia',
            name='tablero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia', to='game.tablero'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='game.partida'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='tablero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='game.tablero'),
        ),
        migrations.AlterField(
            model_name='ia',
            name='jugador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ia', serialize=False, to='game.jugador'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='game.jugador'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='pieza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='game.pieza'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='jugador_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_actual', to='game.jugador'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='game.jugador'),
        ),
        migrations.CreateModel(
            name='ParticipacionPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('orden_participacion', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partida')),
            ],
            options={
                'verbose_name_plural': 'Participaciones en Partida',
                'unique_together': {('jugador', 'partida')},
            },
        ),
        migrations.AddField(
            model_name='partida',
            name='jugadores',
            field=models.ManyToManyField(related_name='partidas', through='game.ParticipacionPartida', to='game.jugador'),
        ),
    ]
