# Generated by Django 5.1.7 on 2025-12-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_chatbot_ia_chatbot_tablero_ia_tablero_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticipacionPartida',
            new_name='JugadorPartida',
        ),
    ]
