# Generated by Django 5.1.7 on 2025-12-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_participacionpartida_jugadorpartida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='tablero',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='tablero',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='tablero',
        ),
        migrations.RemoveField(
            model_name='ia',
            name='tablero',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='jugador_actual',
        ),
        migrations.AddField(
            model_name='pieza',
            name='chatbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='game.chatbot'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='ia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='game.ia'),
        ),
        migrations.DeleteModel(
            name='Tablero',
        ),
    ]
