# Generated by Django 5.1.7 on 2025-12-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_chatbot_tablero_remove_pieza_tablero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='inicio',
        ),
    ]
