# Generated by Django 5.1.7 on 2025-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_movimiento_fin_remove_movimiento_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
