# Generated by Django 5.1.7 on 2025-12-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_jugador_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='game.partida'),
        ),
    ]
