# Generated by Django 5.1.7 on 2026-01-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_movimiento_pieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='tiempo_sobrante',
            field=models.IntegerField(default=0),
        ),
    ]
