# Generated by Django 5.0 on 2026-02-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_partida_tiempo_sobrante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieza',
            name='ia',
        ),
    ]
