# Generated by Django 5.0 on 2026-02-09 20:15

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_turno_fin_after_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='destino',
            field=models.CharField(max_length=10, validators=[game.models.validate_position_key]),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='origen',
            field=models.CharField(max_length=10, validators=[game.models.validate_position_key]),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='posicion',
            field=models.CharField(max_length=10, validators=[game.models.validate_position_key]),
        ),
    ]
