# Generated by Django 5.0 on 2026-02-09 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_movimiento_destino_alter_movimiento_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia',
            name='nivel',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='jugadorpartida',
            name='orden_participacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddConstraint(
            model_name='ia',
            constraint=models.CheckConstraint(check=models.Q(('nivel__gte', 1), ('nivel__lte', 2)), name='ia_nivel_between_1_2'),
        ),
        migrations.AddConstraint(
            model_name='jugadorpartida',
            constraint=models.UniqueConstraint(fields=('partida', 'orden_participacion'), name='jugadorpartida_unique_orden_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='jugadorpartida',
            constraint=models.CheckConstraint(check=models.Q(('orden_participacion__gte', 1), ('orden_participacion__lte', 6)), name='jugadorpartida_orden_between_1_6'),
        ),
    ]
