# Generated by Copilot (manual migration)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_remove_pieza_ia"),
    ]

    operations = [
        # --- Turno -> Ronda ---
        migrations.RenameModel(
            old_name="Turno",
            new_name="Ronda",
        ),
        migrations.RenameField(
            model_name="ronda",
            old_name="id_turno",
            new_name="id_ronda",
        ),
        migrations.RenameField(
            model_name="movimiento",
            old_name="turno",
            new_name="ronda",
        ),
        migrations.RemoveConstraint(
            model_name="ronda",
            name="turno_fin_after_inicio",
        ),
        migrations.AddConstraint(
            model_name="ronda",
            constraint=models.CheckConstraint(
                check=models.Q(fin__isnull=True) | models.Q(fin__gt=models.F("inicio")),
                name="ronda_fin_after_inicio",
            ),
        ),

        # --- IA -> AgenteInteligente ---
        migrations.RenameModel(
            old_name="IA",
            new_name="AgenteInteligente",
        ),
        migrations.RenameField(
            model_name="chatbot",
            old_name="ia",
            new_name="agente_inteligente",
        ),
        migrations.RemoveConstraint(
            model_name="agenteinteligente",
            name="ia_nivel_between_1_2",
        ),
        migrations.AddConstraint(
            model_name="agenteinteligente",
            constraint=models.CheckConstraint(
                check=models.Q(nivel__gte=1) & models.Q(nivel__lte=2),
                name="agenteinteligente_nivel_between_1_2",
            ),
        ),
    ]
