# Generated by Django 5.0 on 2026-04-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_rename_turno_to_ronda_and_ia_to_agenteinteligente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenteinteligente',
            options={'verbose_name': 'Agente Inteligente', 'verbose_name_plural': 'Agentes Inteligentes'},
        ),
        migrations.AlterModelOptions(
            name='ronda',
            options={'verbose_name_plural': 'Rondas'},
        ),
        migrations.AlterField(
            model_name='agenteinteligente',
            name='jugador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agente_inteligente', serialize=False, to='game.jugador'),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='game.jugador'),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='game.partida'),
        ),
    ]
