# Generated by Django 5.0 on 2026-04-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_agenteinteligente_options_alter_ronda_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='agente_inteligente',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='contexto',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='game.jugador'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='game.partida'),
        ),
    ]
