# Generated by Django 5.0 on 2026-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_chatbot_agente_inteligente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Indica si es una partida de demostración (accesible desde el tutorial)'),
        ),
    ]
