# Generated by Django 5.0 on 2026-05-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_partida_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
