# Generated by Django 5.0 on 2026-05-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_partida_is_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieza',
            name='chatbot',
        ),
    ]
